Fix issues involving sudo and root.
Edu4rdSHL/archlinux-pkgrecover pull request #1
Opened 2024-09-22 21:57 UTC by mrhoomanwastaken

Removed the usage of sudo in the script because it stops pacman from running. 
The script will now warn you if you are not root, but it will not stop the script from running to allow usage of dry-run without root privileges.

2024-09-22 22:36 UTC, mrhoomanwastaken commented
Also added a directory check to stop it from breaking everything if the drive is not mounted properly.

2024-09-22 22:48 UTC, Edu4rdSHL requested changes
Thank you so much for this PR, for some reason I left the `sudo` hardcoded there even when I hate it on scripts... everything looks good to me, but I think it makes sense to bail out if `--dry-run` is not specified and we don't have root privileges.

2024-09-23 00:57 UTC, mrhoomanwastaken commented
I will do that.
The only reason I did not code it to bail out without --dry-run is because pacman will already stop anyone who is not root and I just saw it as redundant.

2024-09-23 05:05 UTC, Edu4rdSHL approved these changes

2024-09-23 05:06 UTC, merged

2024-09-23 05:06 UTC, Edu4rdSHL commented
Ty!